name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "develop","master" ]

permissions:
  contents: read

concurrency:
  group: backend-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK 21
        uses: actions/setup-node@v6
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Grant execute permission to Maven wrapper
        run: chmod +x ./mvnw

      - name: Build with Maven
        run: ./mvnw --batch-mode --no-transfer-progress clean verify